/** Generated by YAKINDU Statechart Tools code generator. */

#include "Path_finding.h"
#include "../src/sc_types.h"

/*! \file Implementation of the state machine 'path_finding'
*/

/* prototypes of all internal functions */
static void enact_main_region_Station(Path_finding* handle);
static void enact_main_region_Following(Path_finding* handle);
static void exact_main_region_Following(Path_finding* handle);
static void enseq_main_region_Station_default(Path_finding* handle);
static void enseq_main_region_Following_default(Path_finding* handle);
static void enseq_main_region_default(Path_finding* handle);
static void exseq_main_region_Station(Path_finding* handle);
static void exseq_main_region_Following(Path_finding* handle);
static void exseq_main_region(Path_finding* handle);
static void react_main_region__entry_Default(Path_finding* handle);
static sc_boolean react(Path_finding* handle);
static sc_boolean main_region_Station_react(Path_finding* handle, const sc_boolean try_transition);
static sc_boolean main_region_Following_react(Path_finding* handle, const sc_boolean try_transition);
static void clearInEvents(Path_finding* handle);
static void clearOutEvents(Path_finding* handle);


void path_finding_init(Path_finding* handle)
{
	sc_integer i;
	
	for (i = 0; i < PATH_FINDING_MAX_ORTHOGONAL_STATES; ++i)
	{
		handle->stateConfVector[i] = Path_finding_last_state;
	}
	
	
	handle->stateConfVectorPosition = 0;
	
	clearInEvents(handle);
	clearOutEvents(handle);
	
	/* Default init sequence for statechart path_finding */
	handle->iface.speed_left = 0;
	handle->iface.speed_right = 0;
	handle->iface.has_vec = bool_false;
	handle->iface.v_start_x = 0;
	handle->iface.v_start_y = 0;
	handle->iface.v_end_x = 0;
	handle->iface.v_end_y = 0;
}

void path_finding_enter(Path_finding* handle)
{
	/* Default enter sequence for statechart path_finding */
	enseq_main_region_default(handle);
}

void path_finding_runCycle(Path_finding* handle)
{
	clearOutEvents(handle);
	for (handle->stateConfVectorPosition = 0;
		handle->stateConfVectorPosition < PATH_FINDING_MAX_ORTHOGONAL_STATES;
		handle->stateConfVectorPosition++)
		{
			
		switch (handle->stateConfVector[handle->stateConfVectorPosition])
		{
		case Path_finding_main_region_Station:
		{
			main_region_Station_react(handle, bool_true);
			break;
		}
		case Path_finding_main_region_Following:
		{
			main_region_Following_react(handle, bool_true);
			break;
		}
		default:
			break;
		}
	}
	
	clearInEvents(handle);
}

void path_finding_exit(Path_finding* handle)
{
	/* Default exit sequence for statechart path_finding */
	exseq_main_region(handle);
}

sc_boolean path_finding_isActive(const Path_finding* handle)
{
	sc_boolean result = bool_false;
	sc_integer i;
	
	for(i = 0; i < PATH_FINDING_MAX_ORTHOGONAL_STATES; i++)
	{
		result = result || handle->stateConfVector[i] != Path_finding_last_state;
	}
	
	return result;
}

/* 
 * Always returns 'false' since this state machine can never become final.
 */
sc_boolean path_finding_isFinal(const Path_finding* handle)
{
(void)(handle);
return bool_false;

}

sc_boolean path_finding_isStateActive(const Path_finding* handle, Path_findingStates state)
{
	sc_boolean result = bool_false;
	switch (state)
	{
		case Path_finding_main_region_Station :
			result = (sc_boolean) (handle->stateConfVector[SCVI_PATH_FINDING_MAIN_REGION_STATION] == Path_finding_main_region_Station
			);
			break;
		case Path_finding_main_region_Following :
			result = (sc_boolean) (handle->stateConfVector[SCVI_PATH_FINDING_MAIN_REGION_FOLLOWING] == Path_finding_main_region_Following
			);
			break;
		default:
			result = bool_false;
			break;
	}
	return result;
}

static void clearInEvents(Path_finding* handle)
{
}

static void clearOutEvents(Path_finding* handle)
{
}



int16_t path_findingIface_get_speed_left(const Path_finding* handle)
{
	return handle->iface.speed_left;
}
void path_findingIface_set_speed_left(Path_finding* handle, int16_t value)
{
	handle->iface.speed_left = value;
}
int16_t path_findingIface_get_speed_right(const Path_finding* handle)
{
	return handle->iface.speed_right;
}
void path_findingIface_set_speed_right(Path_finding* handle, int16_t value)
{
	handle->iface.speed_right = value;
}
sc_boolean path_findingIface_get_has_vec(const Path_finding* handle)
{
	return handle->iface.has_vec;
}
void path_findingIface_set_has_vec(Path_finding* handle, sc_boolean value)
{
	handle->iface.has_vec = value;
}
uint8_t path_findingIface_get_v_start_x(const Path_finding* handle)
{
	return handle->iface.v_start_x;
}
void path_findingIface_set_v_start_x(Path_finding* handle, uint8_t value)
{
	handle->iface.v_start_x = value;
}
uint8_t path_findingIface_get_v_start_y(const Path_finding* handle)
{
	return handle->iface.v_start_y;
}
void path_findingIface_set_v_start_y(Path_finding* handle, uint8_t value)
{
	handle->iface.v_start_y = value;
}
uint8_t path_findingIface_get_v_end_x(const Path_finding* handle)
{
	return handle->iface.v_end_x;
}
void path_findingIface_set_v_end_x(Path_finding* handle, uint8_t value)
{
	handle->iface.v_end_x = value;
}
uint8_t path_findingIface_get_v_end_y(const Path_finding* handle)
{
	return handle->iface.v_end_y;
}
void path_findingIface_set_v_end_y(Path_finding* handle, uint8_t value)
{
	handle->iface.v_end_y = value;
}

/* implementations of all internal functions */

/* Entry action for state 'Station'. */
static void enact_main_region_Station(Path_finding* handle)
{
	/* Entry action for state 'Station'. */
	lcd_printf(0, "NO LINE");
}

/* Entry action for state 'Following'. */
static void enact_main_region_Following(Path_finding* handle)
{
	/* Entry action for state 'Following'. */
	lcd_printf(0, "FOLLOWING");
	handle->iface.speed_left = 150;
	handle->iface.speed_right = 150;
}

/* Exit action for state 'Following'. */
static void exact_main_region_Following(Path_finding* handle)
{
	/* Exit action for state 'Following'. */
	lcd_printf(1, "           ");
	stop_kobuki();
}

/* 'default' enter sequence for state Station */
static void enseq_main_region_Station_default(Path_finding* handle)
{
	/* 'default' enter sequence for state Station */
	enact_main_region_Station(handle);
	handle->stateConfVector[0] = Path_finding_main_region_Station;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state Following */
static void enseq_main_region_Following_default(Path_finding* handle)
{
	/* 'default' enter sequence for state Following */
	enact_main_region_Following(handle);
	handle->stateConfVector[0] = Path_finding_main_region_Following;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for region main region */
static void enseq_main_region_default(Path_finding* handle)
{
	/* 'default' enter sequence for region main region */
	react_main_region__entry_Default(handle);
}

/* Default exit sequence for state Station */
static void exseq_main_region_Station(Path_finding* handle)
{
	/* Default exit sequence for state Station */
	handle->stateConfVector[0] = Path_finding_last_state;
	handle->stateConfVectorPosition = 0;
}

/* Default exit sequence for state Following */
static void exseq_main_region_Following(Path_finding* handle)
{
	/* Default exit sequence for state Following */
	handle->stateConfVector[0] = Path_finding_last_state;
	handle->stateConfVectorPosition = 0;
	exact_main_region_Following(handle);
}

/* Default exit sequence for region main region */
static void exseq_main_region(Path_finding* handle)
{
	/* Default exit sequence for region main region */
	/* Handle exit of all possible states (of path_finding.main_region) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case Path_finding_main_region_Station :
		{
			exseq_main_region_Station(handle);
			break;
		}
		case Path_finding_main_region_Following :
		{
			exseq_main_region_Following(handle);
			break;
		}
		default: break;
	}
}

/* Default react sequence for initial entry  */
static void react_main_region__entry_Default(Path_finding* handle)
{
	/* Default react sequence for initial entry  */
	enseq_main_region_Station_default(handle);
}

static sc_boolean react(Path_finding* handle) {
	/* State machine reactions. */
	return bool_false;
}

static sc_boolean main_region_Station_react(Path_finding* handle, const sc_boolean try_transition) {
	/* The reactions of state Station. */
	sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if ((react(handle)) == (bool_false))
		{ 
			if (handle->iface.has_vec == bool_true)
			{ 
				exseq_main_region_Station(handle);
				enseq_main_region_Following_default(handle);
			}  else
			{
				did_transition = bool_false;
			}
		} 
	} 
	if ((did_transition) == (bool_false))
	{ 
		stop_kobuki();
		handle->iface.has_vec = is_vec_detected();
	} 
	return did_transition;
}

static sc_boolean main_region_Following_react(Path_finding* handle, const sc_boolean try_transition) {
	/* The reactions of state Following. */
	sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if ((react(handle)) == (bool_false))
		{ 
			if (handle->iface.has_vec == bool_false)
			{ 
				exseq_main_region_Following(handle);
				enseq_main_region_Station_default(handle);
			}  else
			{
				did_transition = bool_false;
			}
		} 
	} 
	if ((did_transition) == (bool_false))
	{ 
		handle->iface.has_vec = is_vec_detected();
		handle->iface.v_start_x = vec_start_x();
		handle->iface.v_start_y = vec_start_y();
		handle->iface.v_end_x = vec_end_x();
		handle->iface.v_end_y = vec_end_y();
		lcd_printf(0, "FOLLOWING %d %d", handle->iface.v_end_x, handle->iface.v_end_y);
		handle->iface.speed_left = (((handle->iface.v_end_x) > (120)) && ((handle->iface.v_end_x) < (134))) ? 150 : handle->iface.speed_left;
		handle->iface.speed_right = (((handle->iface.v_end_x) > (120)) && ((handle->iface.v_end_x) < (134))) ? 150 : handle->iface.speed_right;
		handle->iface.speed_right += ((handle->iface.v_end_x) <= (120)) ? 3 : 0;
		handle->iface.speed_left += ((handle->iface.v_end_x) >= (134)) ? 3 : 0;
		lcd_printf(1, "SPEED %d %d", handle->iface.speed_left, handle->iface.speed_right);
		drive_kobuki(handle->iface.speed_left, handle->iface.speed_right);
	} 
	return did_transition;
}


