/** Generated by YAKINDU Statechart Tools code generator. */

#include "Path_finding.h"
#include "../src/sc_types.h"

/*! \file Implementation of the state machine 'path_finding'
*/

/* prototypes of all internal functions */
static void enact_main_region_OFF(Path_finding* handle);
static void enact_main_region_DRIVING(Path_finding* handle);
static void enact_main_region_LEFT(Path_finding* handle);
static void enact_main_region_RIGHT(Path_finding* handle);
static void enseq_main_region_OFF_default(Path_finding* handle);
static void enseq_main_region_DRIVING_default(Path_finding* handle);
static void enseq_main_region_LEFT_default(Path_finding* handle);
static void enseq_main_region_RIGHT_default(Path_finding* handle);
static void enseq_main_region_default(Path_finding* handle);
static void exseq_main_region_OFF(Path_finding* handle);
static void exseq_main_region_DRIVING(Path_finding* handle);
static void exseq_main_region_LEFT(Path_finding* handle);
static void exseq_main_region_RIGHT(Path_finding* handle);
static void exseq_main_region(Path_finding* handle);
static void react_main_region__entry_Default(Path_finding* handle);
static sc_boolean react(Path_finding* handle);
static sc_boolean main_region_OFF_react(Path_finding* handle, const sc_boolean try_transition);
static sc_boolean main_region_DRIVING_react(Path_finding* handle, const sc_boolean try_transition);
static sc_boolean main_region_LEFT_react(Path_finding* handle, const sc_boolean try_transition);
static sc_boolean main_region_RIGHT_react(Path_finding* handle, const sc_boolean try_transition);
static void clearInEvents(Path_finding* handle);
static void clearOutEvents(Path_finding* handle);


void path_finding_init(Path_finding* handle)
{
	sc_integer i;
	
	for (i = 0; i < PATH_FINDING_MAX_ORTHOGONAL_STATES; ++i)
	{
		handle->stateConfVector[i] = Path_finding_last_state;
	}
	
	
	handle->stateConfVectorPosition = 0;
	
	clearInEvents(handle);
	clearOutEvents(handle);
	
	/* Default init sequence for statechart path_finding */
	handle->iface.button = bool_false;
	handle->iface.prev_encoder = 0;
	handle->iface.angle = 0.0f;
	handle->iface.cliffLeft = bool_false;
	handle->iface.cliffRight = bool_false;
	handle->iface.theta = 0.0f;
	handle->iface.psi = 0.0f;
	handle->iface.dist = 0.0f;
	handle->iface.x_off = 0.0f;
}

void path_finding_enter(Path_finding* handle)
{
	/* Default enter sequence for statechart path_finding */
	enseq_main_region_default(handle);
}

void path_finding_runCycle(Path_finding* handle)
{
	clearOutEvents(handle);
	for (handle->stateConfVectorPosition = 0;
		handle->stateConfVectorPosition < PATH_FINDING_MAX_ORTHOGONAL_STATES;
		handle->stateConfVectorPosition++)
		{
			
		switch (handle->stateConfVector[handle->stateConfVectorPosition])
		{
		case Path_finding_main_region_OFF:
		{
			main_region_OFF_react(handle, bool_true);
			break;
		}
		case Path_finding_main_region_DRIVING:
		{
			main_region_DRIVING_react(handle, bool_true);
			break;
		}
		case Path_finding_main_region_LEFT:
		{
			main_region_LEFT_react(handle, bool_true);
			break;
		}
		case Path_finding_main_region_RIGHT:
		{
			main_region_RIGHT_react(handle, bool_true);
			break;
		}
		default:
			break;
		}
	}
	
	clearInEvents(handle);
}

void path_finding_exit(Path_finding* handle)
{
	/* Default exit sequence for statechart path_finding */
	exseq_main_region(handle);
}

sc_boolean path_finding_isActive(const Path_finding* handle)
{
	sc_boolean result = bool_false;
	sc_integer i;
	
	for(i = 0; i < PATH_FINDING_MAX_ORTHOGONAL_STATES; i++)
	{
		result = result || handle->stateConfVector[i] != Path_finding_last_state;
	}
	
	return result;
}

/* 
 * Always returns 'false' since this state machine can never become final.
 */
sc_boolean path_finding_isFinal(const Path_finding* handle)
{
(void)(handle);
return bool_false;

}

sc_boolean path_finding_isStateActive(const Path_finding* handle, Path_findingStates state)
{
	sc_boolean result = bool_false;
	switch (state)
	{
		case Path_finding_main_region_OFF :
			result = (sc_boolean) (handle->stateConfVector[SCVI_PATH_FINDING_MAIN_REGION_OFF] == Path_finding_main_region_OFF
			);
			break;
		case Path_finding_main_region_DRIVING :
			result = (sc_boolean) (handle->stateConfVector[SCVI_PATH_FINDING_MAIN_REGION_DRIVING] == Path_finding_main_region_DRIVING
			);
			break;
		case Path_finding_main_region_LEFT :
			result = (sc_boolean) (handle->stateConfVector[SCVI_PATH_FINDING_MAIN_REGION_LEFT] == Path_finding_main_region_LEFT
			);
			break;
		case Path_finding_main_region_RIGHT :
			result = (sc_boolean) (handle->stateConfVector[SCVI_PATH_FINDING_MAIN_REGION_RIGHT] == Path_finding_main_region_RIGHT
			);
			break;
		default:
			result = bool_false;
			break;
	}
	return result;
}

static void clearInEvents(Path_finding* handle)
{
}

static void clearOutEvents(Path_finding* handle)
{
}



sc_boolean path_findingIface_get_button(const Path_finding* handle)
{
	return handle->iface.button;
}
void path_findingIface_set_button(Path_finding* handle, sc_boolean value)
{
	handle->iface.button = value;
}
uint16_t path_findingIface_get_prev_encoder(const Path_finding* handle)
{
	return handle->iface.prev_encoder;
}
void path_findingIface_set_prev_encoder(Path_finding* handle, uint16_t value)
{
	handle->iface.prev_encoder = value;
}
float path_findingIface_get_angle(const Path_finding* handle)
{
	return handle->iface.angle;
}
void path_findingIface_set_angle(Path_finding* handle, float value)
{
	handle->iface.angle = value;
}
sc_boolean path_findingIface_get_cliffLeft(const Path_finding* handle)
{
	return handle->iface.cliffLeft;
}
void path_findingIface_set_cliffLeft(Path_finding* handle, sc_boolean value)
{
	handle->iface.cliffLeft = value;
}
sc_boolean path_findingIface_get_cliffRight(const Path_finding* handle)
{
	return handle->iface.cliffRight;
}
void path_findingIface_set_cliffRight(Path_finding* handle, sc_boolean value)
{
	handle->iface.cliffRight = value;
}
float path_findingIface_get_theta(const Path_finding* handle)
{
	return handle->iface.theta;
}
void path_findingIface_set_theta(Path_finding* handle, float value)
{
	handle->iface.theta = value;
}
float path_findingIface_get_psi(const Path_finding* handle)
{
	return handle->iface.psi;
}
void path_findingIface_set_psi(Path_finding* handle, float value)
{
	handle->iface.psi = value;
}
float path_findingIface_get_dist(const Path_finding* handle)
{
	return handle->iface.dist;
}
void path_findingIface_set_dist(Path_finding* handle, float value)
{
	handle->iface.dist = value;
}
float path_findingIface_get_x_off(const Path_finding* handle)
{
	return handle->iface.x_off;
}
void path_findingIface_set_x_off(Path_finding* handle, float value)
{
	handle->iface.x_off = value;
}

/* implementations of all internal functions */

/* Entry action for state 'OFF'. */
static void enact_main_region_OFF(Path_finding* handle)
{
	/* Entry action for state 'OFF'. */
	handle->iface.button = bool_false;
}

/* Entry action for state 'DRIVING'. */
static void enact_main_region_DRIVING(Path_finding* handle)
{
	/* Entry action for state 'DRIVING'. */
	handle->iface.button = bool_false;
	handle->iface.theta = 0.0f;
}

/* Entry action for state 'LEFT'. */
static void enact_main_region_LEFT(Path_finding* handle)
{
	/* Entry action for state 'LEFT'. */
	handle->iface.button = bool_false;
}

/* Entry action for state 'RIGHT'. */
static void enact_main_region_RIGHT(Path_finding* handle)
{
	/* Entry action for state 'RIGHT'. */
	handle->iface.button = bool_false;
}

/* 'default' enter sequence for state OFF */
static void enseq_main_region_OFF_default(Path_finding* handle)
{
	/* 'default' enter sequence for state OFF */
	enact_main_region_OFF(handle);
	handle->stateConfVector[0] = Path_finding_main_region_OFF;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state DRIVING */
static void enseq_main_region_DRIVING_default(Path_finding* handle)
{
	/* 'default' enter sequence for state DRIVING */
	enact_main_region_DRIVING(handle);
	handle->stateConfVector[0] = Path_finding_main_region_DRIVING;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state LEFT */
static void enseq_main_region_LEFT_default(Path_finding* handle)
{
	/* 'default' enter sequence for state LEFT */
	enact_main_region_LEFT(handle);
	handle->stateConfVector[0] = Path_finding_main_region_LEFT;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state RIGHT */
static void enseq_main_region_RIGHT_default(Path_finding* handle)
{
	/* 'default' enter sequence for state RIGHT */
	enact_main_region_RIGHT(handle);
	handle->stateConfVector[0] = Path_finding_main_region_RIGHT;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for region main region */
static void enseq_main_region_default(Path_finding* handle)
{
	/* 'default' enter sequence for region main region */
	react_main_region__entry_Default(handle);
}

/* Default exit sequence for state OFF */
static void exseq_main_region_OFF(Path_finding* handle)
{
	/* Default exit sequence for state OFF */
	handle->stateConfVector[0] = Path_finding_last_state;
	handle->stateConfVectorPosition = 0;
}

/* Default exit sequence for state DRIVING */
static void exseq_main_region_DRIVING(Path_finding* handle)
{
	/* Default exit sequence for state DRIVING */
	handle->stateConfVector[0] = Path_finding_last_state;
	handle->stateConfVectorPosition = 0;
}

/* Default exit sequence for state LEFT */
static void exseq_main_region_LEFT(Path_finding* handle)
{
	/* Default exit sequence for state LEFT */
	handle->stateConfVector[0] = Path_finding_last_state;
	handle->stateConfVectorPosition = 0;
}

/* Default exit sequence for state RIGHT */
static void exseq_main_region_RIGHT(Path_finding* handle)
{
	/* Default exit sequence for state RIGHT */
	handle->stateConfVector[0] = Path_finding_last_state;
	handle->stateConfVectorPosition = 0;
}

/* Default exit sequence for region main region */
static void exseq_main_region(Path_finding* handle)
{
	/* Default exit sequence for region main region */
	/* Handle exit of all possible states (of path_finding.main_region) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case Path_finding_main_region_OFF :
		{
			exseq_main_region_OFF(handle);
			break;
		}
		case Path_finding_main_region_DRIVING :
		{
			exseq_main_region_DRIVING(handle);
			break;
		}
		case Path_finding_main_region_LEFT :
		{
			exseq_main_region_LEFT(handle);
			break;
		}
		case Path_finding_main_region_RIGHT :
		{
			exseq_main_region_RIGHT(handle);
			break;
		}
		default: break;
	}
}

/* Default react sequence for initial entry  */
static void react_main_region__entry_Default(Path_finding* handle)
{
	/* Default react sequence for initial entry  */
	enseq_main_region_OFF_default(handle);
}

static sc_boolean react(Path_finding* handle) {
	/* State machine reactions. */
	return bool_false;
}

static sc_boolean main_region_OFF_react(Path_finding* handle, const sc_boolean try_transition) {
	/* The reactions of state OFF. */
	sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if ((react(handle)) == (bool_false))
		{ 
			if (handle->iface.button == bool_true)
			{ 
				exseq_main_region_OFF(handle);
				enseq_main_region_DRIVING_default(handle);
			}  else
			{
				did_transition = bool_false;
			}
		} 
	} 
	if ((did_transition) == (bool_false))
	{ 
		stop_kobuki();
		handle->iface.button = is_button_press();
		lcd_printf(0, "OFF");
		lcd_printf(1, "Theta: %f", read_tilt_theta());
	} 
	return did_transition;
}

static sc_boolean main_region_DRIVING_react(Path_finding* handle, const sc_boolean try_transition) {
	/* The reactions of state DRIVING. */
	sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if ((react(handle)) == (bool_false))
		{ 
			if ((handle->iface.theta) > (10))
			{ 
				exseq_main_region_DRIVING(handle);
				enseq_main_region_LEFT_default(handle);
			}  else
			{
				if ((handle->iface.theta) < (10))
				{ 
					exseq_main_region_DRIVING(handle);
					enseq_main_region_RIGHT_default(handle);
				}  else
				{
					did_transition = bool_false;
				}
			}
		} 
	} 
	if ((did_transition) == (bool_false))
	{ 
		drive_kobuki(150, 150);
		lcd_printf(0, "DRIVING");
		handle->iface.button = is_button_press();
		handle->iface.theta = get_line_tracking_theta();
	} 
	return did_transition;
}

static sc_boolean main_region_LEFT_react(Path_finding* handle, const sc_boolean try_transition) {
	/* The reactions of state LEFT. */
	sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if ((react(handle)) == (bool_false))
		{ 
			if (((handle->iface.theta) < (10)) && ((handle->iface.theta) > (0)))
			{ 
				exseq_main_region_LEFT(handle);
				enseq_main_region_DRIVING_default(handle);
			}  else
			{
				did_transition = bool_false;
			}
		} 
	} 
	if ((did_transition) == (bool_false))
	{ 
		drive_kobuki(100, 150);
		lcd_printf(0, "TURN LEFT");
		handle->iface.button = is_button_press();
		handle->iface.theta = get_line_tracking_theta();
	} 
	return did_transition;
}

static sc_boolean main_region_RIGHT_react(Path_finding* handle, const sc_boolean try_transition) {
	/* The reactions of state RIGHT. */
	sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if ((react(handle)) == (bool_false))
		{ 
			if (((handle->iface.theta) < (10)) && ((handle->iface.theta) > (0)))
			{ 
				exseq_main_region_RIGHT(handle);
				enseq_main_region_DRIVING_default(handle);
			}  else
			{
				did_transition = bool_false;
			}
		} 
	} 
	if ((did_transition) == (bool_false))
	{ 
		drive_kobuki(150, 100);
		lcd_printf(0, "TURN RIGHT");
		handle->iface.button = is_button_press();
		handle->iface.theta = get_line_tracking_theta();
	} 
	return did_transition;
}


