/** Generated by YAKINDU Statechart Tools code generator. */

#ifndef PATH_FINDING_H_
#define PATH_FINDING_H_

#include "../platform_kobuki.h"
#include "../helper_funcs.h"
#include "../src/sc_types.h"

#ifdef __cplusplus
extern "C" { 
#endif 

/*! \file Header of the state machine 'path_finding'.
*/

/*! Define number of states in the state enum */

#define PATH_FINDING_STATE_COUNT 4

/*! Define dimension of the state configuration vector for orthogonal states. */
#define PATH_FINDING_MAX_ORTHOGONAL_STATES 1


/*! Define indices of states in the StateConfVector */
#define SCVI_PATH_FINDING_MAIN_REGION_OFF 0
#define SCVI_PATH_FINDING_MAIN_REGION_DRIVING 0
#define SCVI_PATH_FINDING_MAIN_REGION_LEFT 0
#define SCVI_PATH_FINDING_MAIN_REGION_RIGHT 0

/*! Enumeration of all states */ 
typedef enum
{
	Path_finding_last_state,
	Path_finding_main_region_OFF,
	Path_finding_main_region_DRIVING,
	Path_finding_main_region_LEFT,
	Path_finding_main_region_RIGHT
} Path_findingStates;







/*! Type definition of the data structure for the Path_findingIface interface scope. */
typedef struct
{
	sc_boolean button;
	uint16_t prev_encoder;
	float angle;
	sc_boolean cliffLeft;
	sc_boolean cliffRight;
	float theta;
	float psi;
	float dist;
	float x_off;
} Path_findingIface;




/*! 
 * Type definition of the data structure for the Path_finding state machine.
 * This data structure has to be allocated by the client code. 
 */
typedef struct
{
	Path_findingStates stateConfVector[PATH_FINDING_MAX_ORTHOGONAL_STATES];
	sc_ushort stateConfVectorPosition; 
	
	Path_findingIface iface;
} Path_finding;



/*! Initializes the Path_finding state machine data structures. Must be called before first usage.*/
extern void path_finding_init(Path_finding* handle);

/*! Activates the state machine */
extern void path_finding_enter(Path_finding* handle);

/*! Deactivates the state machine */
extern void path_finding_exit(Path_finding* handle);

/*! Performs a 'run to completion' step. */
extern void path_finding_runCycle(Path_finding* handle);


/*! Gets the value of the variable 'button' that is defined in the default interface scope. */ 
extern sc_boolean path_findingIface_get_button(const Path_finding* handle);
/*! Sets the value of the variable 'button' that is defined in the default interface scope. */ 
extern void path_findingIface_set_button(Path_finding* handle, sc_boolean value);
/*! Gets the value of the variable 'prev_encoder' that is defined in the default interface scope. */ 
extern uint16_t path_findingIface_get_prev_encoder(const Path_finding* handle);
/*! Sets the value of the variable 'prev_encoder' that is defined in the default interface scope. */ 
extern void path_findingIface_set_prev_encoder(Path_finding* handle, uint16_t value);
/*! Gets the value of the variable 'angle' that is defined in the default interface scope. */ 
extern float path_findingIface_get_angle(const Path_finding* handle);
/*! Sets the value of the variable 'angle' that is defined in the default interface scope. */ 
extern void path_findingIface_set_angle(Path_finding* handle, float value);
/*! Gets the value of the variable 'cliffLeft' that is defined in the default interface scope. */ 
extern sc_boolean path_findingIface_get_cliffLeft(const Path_finding* handle);
/*! Sets the value of the variable 'cliffLeft' that is defined in the default interface scope. */ 
extern void path_findingIface_set_cliffLeft(Path_finding* handle, sc_boolean value);
/*! Gets the value of the variable 'cliffRight' that is defined in the default interface scope. */ 
extern sc_boolean path_findingIface_get_cliffRight(const Path_finding* handle);
/*! Sets the value of the variable 'cliffRight' that is defined in the default interface scope. */ 
extern void path_findingIface_set_cliffRight(Path_finding* handle, sc_boolean value);
/*! Gets the value of the variable 'theta' that is defined in the default interface scope. */ 
extern float path_findingIface_get_theta(const Path_finding* handle);
/*! Sets the value of the variable 'theta' that is defined in the default interface scope. */ 
extern void path_findingIface_set_theta(Path_finding* handle, float value);
/*! Gets the value of the variable 'psi' that is defined in the default interface scope. */ 
extern float path_findingIface_get_psi(const Path_finding* handle);
/*! Sets the value of the variable 'psi' that is defined in the default interface scope. */ 
extern void path_findingIface_set_psi(Path_finding* handle, float value);
/*! Gets the value of the variable 'dist' that is defined in the default interface scope. */ 
extern float path_findingIface_get_dist(const Path_finding* handle);
/*! Sets the value of the variable 'dist' that is defined in the default interface scope. */ 
extern void path_findingIface_set_dist(Path_finding* handle, float value);
/*! Gets the value of the variable 'x_off' that is defined in the default interface scope. */ 
extern float path_findingIface_get_x_off(const Path_finding* handle);
/*! Sets the value of the variable 'x_off' that is defined in the default interface scope. */ 
extern void path_findingIface_set_x_off(Path_finding* handle, float value);

/*!
 * Checks whether the state machine is active (until 2.4.1 this method was used for states).
 * A state machine is active if it was entered. It is inactive if it has not been entered at all or if it has been exited.
 */
extern sc_boolean path_finding_isActive(const Path_finding* handle);

/*!
 * Checks if all active states are final. 
 * If there are no active states then the state machine is considered being inactive. In this case this method returns false.
 */
extern sc_boolean path_finding_isFinal(const Path_finding* handle);

/*! Checks if the specified state is active (until 2.4.1 the used method for states was called isActive()). */
extern sc_boolean path_finding_isStateActive(const Path_finding* handle, Path_findingStates state);


#ifdef __cplusplus
}
#endif 

#endif /* PATH_FINDING_H_ */
