/** Generated by YAKINDU Statechart Tools code generator. */

#include "Rotate.h"
#include "../src/sc_types.h"

/*! \file Implementation of the state machine 'rotate'
*/

/* prototypes of all internal functions */
static void enact_main_region_Rest(Rotate* handle);
static void enact_main_region_Rotating_Left(Rotate* handle);
static void enact_main_region_Rotating_Right(Rotate* handle);
static void exact_main_region_Rest(Rotate* handle);
static void exact_main_region_Rotating_Left(Rotate* handle);
static void exact_main_region_Rotating_Right(Rotate* handle);
static void enseq_main_region_Rest_default(Rotate* handle);
static void enseq_main_region_Rotating_Left_default(Rotate* handle);
static void enseq_main_region_Rotating_Right_default(Rotate* handle);
static void enseq_main_region_default(Rotate* handle);
static void exseq_main_region_Rest(Rotate* handle);
static void exseq_main_region_Rotating_Left(Rotate* handle);
static void exseq_main_region_Rotating_Right(Rotate* handle);
static void exseq_main_region(Rotate* handle);
static void react_main_region__entry_Default(Rotate* handle);
static sc_boolean react(Rotate* handle);
static sc_boolean main_region_Rest_react(Rotate* handle, const sc_boolean try_transition);
static sc_boolean main_region_Rotating_Left_react(Rotate* handle, const sc_boolean try_transition);
static sc_boolean main_region_Rotating_Right_react(Rotate* handle, const sc_boolean try_transition);
static void clearInEvents(Rotate* handle);
static void clearOutEvents(Rotate* handle);


void rotate_init(Rotate* handle)
{
	sc_integer i;
	
	for (i = 0; i < ROTATE_MAX_ORTHOGONAL_STATES; ++i)
	{
		handle->stateConfVector[i] = Rotate_last_state;
	}
	
	
	handle->stateConfVectorPosition = 0;
	
	clearInEvents(handle);
	clearOutEvents(handle);
	
	/* Default init sequence for statechart rotate */
	handle->iface.rotation = 0.0f;
	handle->iface.rotation_diff = 0.0f;
	handle->iface.rotation_delta = 0.0f;
}

void rotate_enter(Rotate* handle)
{
	/* Default enter sequence for statechart rotate */
	enseq_main_region_default(handle);
}

void rotate_runCycle(Rotate* handle)
{
	clearOutEvents(handle);
	for (handle->stateConfVectorPosition = 0;
		handle->stateConfVectorPosition < ROTATE_MAX_ORTHOGONAL_STATES;
		handle->stateConfVectorPosition++)
		{
			
		switch (handle->stateConfVector[handle->stateConfVectorPosition])
		{
		case Rotate_main_region_Rest:
		{
			main_region_Rest_react(handle, bool_true);
			break;
		}
		case Rotate_main_region_Rotating_Left:
		{
			main_region_Rotating_Left_react(handle, bool_true);
			break;
		}
		case Rotate_main_region_Rotating_Right:
		{
			main_region_Rotating_Right_react(handle, bool_true);
			break;
		}
		default:
			break;
		}
	}
	
	clearInEvents(handle);
}

void rotate_exit(Rotate* handle)
{
	/* Default exit sequence for statechart rotate */
	exseq_main_region(handle);
}

sc_boolean rotate_isActive(const Rotate* handle)
{
	sc_boolean result = bool_false;
	sc_integer i;
	
	for(i = 0; i < ROTATE_MAX_ORTHOGONAL_STATES; i++)
	{
		result = result || handle->stateConfVector[i] != Rotate_last_state;
	}
	
	return result;
}

/* 
 * Always returns 'false' since this state machine can never become final.
 */
sc_boolean rotate_isFinal(const Rotate* handle)
{
(void)(handle);
return bool_false;

}

sc_boolean rotate_isStateActive(const Rotate* handle, RotateStates state)
{
	sc_boolean result = bool_false;
	switch (state)
	{
		case Rotate_main_region_Rest :
			result = (sc_boolean) (handle->stateConfVector[SCVI_ROTATE_MAIN_REGION_REST] == Rotate_main_region_Rest
			);
			break;
		case Rotate_main_region_Rotating_Left :
			result = (sc_boolean) (handle->stateConfVector[SCVI_ROTATE_MAIN_REGION_ROTATING_LEFT] == Rotate_main_region_Rotating_Left
			);
			break;
		case Rotate_main_region_Rotating_Right :
			result = (sc_boolean) (handle->stateConfVector[SCVI_ROTATE_MAIN_REGION_ROTATING_RIGHT] == Rotate_main_region_Rotating_Right
			);
			break;
		default:
			result = bool_false;
			break;
	}
	return result;
}

static void clearInEvents(Rotate* handle)
{
}

static void clearOutEvents(Rotate* handle)
{
}



float rotateIface_get_rotation(const Rotate* handle)
{
	return handle->iface.rotation;
}
void rotateIface_set_rotation(Rotate* handle, float value)
{
	handle->iface.rotation = value;
}
float rotateIface_get_rotation_diff(const Rotate* handle)
{
	return handle->iface.rotation_diff;
}
void rotateIface_set_rotation_diff(Rotate* handle, float value)
{
	handle->iface.rotation_diff = value;
}
float rotateIface_get_rotation_delta(const Rotate* handle)
{
	return handle->iface.rotation_delta;
}
void rotateIface_set_rotation_delta(Rotate* handle, float value)
{
	handle->iface.rotation_delta = value;
}

/* implementations of all internal functions */

/* Entry action for state 'Rest'. */
static void enact_main_region_Rest(Rotate* handle)
{
	/* Entry action for state 'Rest'. */
	handle->iface.rotation_diff = 0.0f;
	lcd_printf(0, "Resting");
}

/* Entry action for state 'Rotating_Left'. */
static void enact_main_region_Rotating_Left(Rotate* handle)
{
	/* Entry action for state 'Rotating_Left'. */
	lcd_printf(0, "Rotating_Left");
	lcd_printf(1, "Rot left: %f", handle->iface.rotation_diff);
	start_gyro();
	stop_kobuki();
}

/* Entry action for state 'Rotating_Right'. */
static void enact_main_region_Rotating_Right(Rotate* handle)
{
	/* Entry action for state 'Rotating_Right'. */
	lcd_printf(0, "Rotating_Right");
	lcd_printf(1, "Rot right: %f", handle->iface.rotation_diff);
	start_gyro();
	stop_kobuki();
}

/* Exit action for state 'Rest'. */
static void exact_main_region_Rest(Rotate* handle)
{
	/* Exit action for state 'Rest'. */
	stop_kobuki();
}

/* Exit action for state 'Rotating_Left'. */
static void exact_main_region_Rotating_Left(Rotate* handle)
{
	/* Exit action for state 'Rotating_Left'. */
	stop_gyro();
	handle->iface.rotation = normalize_rot((handle->iface.rotation + handle->iface.rotation_delta));
	stop_kobuki();
}

/* Exit action for state 'Rotating_Right'. */
static void exact_main_region_Rotating_Right(Rotate* handle)
{
	/* Exit action for state 'Rotating_Right'. */
	stop_gyro();
	handle->iface.rotation = normalize_rot((handle->iface.rotation + handle->iface.rotation_delta));
	stop_kobuki();
}

/* 'default' enter sequence for state Rest */
static void enseq_main_region_Rest_default(Rotate* handle)
{
	/* 'default' enter sequence for state Rest */
	enact_main_region_Rest(handle);
	handle->stateConfVector[0] = Rotate_main_region_Rest;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state Rotating_Left */
static void enseq_main_region_Rotating_Left_default(Rotate* handle)
{
	/* 'default' enter sequence for state Rotating_Left */
	enact_main_region_Rotating_Left(handle);
	handle->stateConfVector[0] = Rotate_main_region_Rotating_Left;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state Rotating_Right */
static void enseq_main_region_Rotating_Right_default(Rotate* handle)
{
	/* 'default' enter sequence for state Rotating_Right */
	enact_main_region_Rotating_Right(handle);
	handle->stateConfVector[0] = Rotate_main_region_Rotating_Right;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for region main region */
static void enseq_main_region_default(Rotate* handle)
{
	/* 'default' enter sequence for region main region */
	react_main_region__entry_Default(handle);
}

/* Default exit sequence for state Rest */
static void exseq_main_region_Rest(Rotate* handle)
{
	/* Default exit sequence for state Rest */
	handle->stateConfVector[0] = Rotate_last_state;
	handle->stateConfVectorPosition = 0;
	exact_main_region_Rest(handle);
}

/* Default exit sequence for state Rotating_Left */
static void exseq_main_region_Rotating_Left(Rotate* handle)
{
	/* Default exit sequence for state Rotating_Left */
	handle->stateConfVector[0] = Rotate_last_state;
	handle->stateConfVectorPosition = 0;
	exact_main_region_Rotating_Left(handle);
}

/* Default exit sequence for state Rotating_Right */
static void exseq_main_region_Rotating_Right(Rotate* handle)
{
	/* Default exit sequence for state Rotating_Right */
	handle->stateConfVector[0] = Rotate_last_state;
	handle->stateConfVectorPosition = 0;
	exact_main_region_Rotating_Right(handle);
}

/* Default exit sequence for region main region */
static void exseq_main_region(Rotate* handle)
{
	/* Default exit sequence for region main region */
	/* Handle exit of all possible states (of rotate.main_region) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case Rotate_main_region_Rest :
		{
			exseq_main_region_Rest(handle);
			break;
		}
		case Rotate_main_region_Rotating_Left :
		{
			exseq_main_region_Rotating_Left(handle);
			break;
		}
		case Rotate_main_region_Rotating_Right :
		{
			exseq_main_region_Rotating_Right(handle);
			break;
		}
		default: break;
	}
}

/* Default react sequence for initial entry  */
static void react_main_region__entry_Default(Rotate* handle)
{
	/* Default react sequence for initial entry  */
	enseq_main_region_Rest_default(handle);
}

static sc_boolean react(Rotate* handle) {
	/* State machine reactions. */
	return bool_false;
}

static sc_boolean main_region_Rest_react(Rotate* handle, const sc_boolean try_transition) {
	/* The reactions of state Rest. */
	sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if ((react(handle)) == (bool_false))
		{ 
			if ((handle->iface.rotation_diff) > (5.0f))
			{ 
				exseq_main_region_Rest(handle);
				enseq_main_region_Rotating_Left_default(handle);
			}  else
			{
				if ((handle->iface.rotation_diff) < (-5.0f))
				{ 
					exseq_main_region_Rest(handle);
					enseq_main_region_Rotating_Right_default(handle);
				}  else
				{
					did_transition = bool_false;
				}
			}
		} 
	} 
	if ((did_transition) == (bool_false))
	{ 
		stop_kobuki();
		handle->iface.rotation_diff = normalize_rot((get_rotate() - handle->iface.rotation));
	} 
	return did_transition;
}

static sc_boolean main_region_Rotating_Left_react(Rotate* handle, const sc_boolean try_transition) {
	/* The reactions of state Rotating_Left. */
	sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if ((react(handle)) == (bool_false))
		{ 
			if ((handle->iface.rotation_delta) > (handle->iface.rotation_diff))
			{ 
				exseq_main_region_Rotating_Left(handle);
				enseq_main_region_Rest_default(handle);
			}  else
			{
				did_transition = bool_false;
			}
		} 
	} 
	if ((did_transition) == (bool_false))
	{ 
		handle->iface.rotation_delta = read_gyro();
		lcd_printf(1, "Rot %f", handle->iface.rotation_delta);
		drive_kobuki(-150, 150);
	} 
	return did_transition;
}

static sc_boolean main_region_Rotating_Right_react(Rotate* handle, const sc_boolean try_transition) {
	/* The reactions of state Rotating_Right. */
	sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if ((react(handle)) == (bool_false))
		{ 
			if ((handle->iface.rotation_delta) < (handle->iface.rotation_diff))
			{ 
				exseq_main_region_Rotating_Right(handle);
				enseq_main_region_Rest_default(handle);
			}  else
			{
				did_transition = bool_false;
			}
		} 
	} 
	if ((did_transition) == (bool_false))
	{ 
		handle->iface.rotation_delta = read_gyro();
		lcd_printf(1, "Rot %f", handle->iface.rotation_delta);
		drive_kobuki(150, -150);
	} 
	return did_transition;
}


