/** Generated by YAKINDU Statechart Tools code generator. */

#include "Robot_template.h"
#include "../src/sc_types.h"

/*! \file Implementation of the state machine 'robot_template'
*/

/* prototypes of all internal functions */
static void enact_main_region_OFF(Robot_template* handle);
static void enact_main_region_DRIVING(Robot_template* handle);
static void enact_main_region_LEFT(Robot_template* handle);
static void enact_main_region_RIGHT(Robot_template* handle);
static void enseq_main_region_OFF_default(Robot_template* handle);
static void enseq_main_region_DRIVING_default(Robot_template* handle);
static void enseq_main_region_LEFT_default(Robot_template* handle);
static void enseq_main_region_RIGHT_default(Robot_template* handle);
static void enseq_main_region_default(Robot_template* handle);
static void exseq_main_region_OFF(Robot_template* handle);
static void exseq_main_region_DRIVING(Robot_template* handle);
static void exseq_main_region_LEFT(Robot_template* handle);
static void exseq_main_region_RIGHT(Robot_template* handle);
static void exseq_main_region(Robot_template* handle);
static void react_main_region__entry_Default(Robot_template* handle);
static sc_boolean react(Robot_template* handle);
static sc_boolean main_region_OFF_react(Robot_template* handle, const sc_boolean try_transition);
static sc_boolean main_region_DRIVING_react(Robot_template* handle, const sc_boolean try_transition);
static sc_boolean main_region_LEFT_react(Robot_template* handle, const sc_boolean try_transition);
static sc_boolean main_region_RIGHT_react(Robot_template* handle, const sc_boolean try_transition);
static void clearInEvents(Robot_template* handle);
static void clearOutEvents(Robot_template* handle);


void robot_template_init(Robot_template* handle)
{
	sc_integer i;
	
	for (i = 0; i < ROBOT_TEMPLATE_MAX_ORTHOGONAL_STATES; ++i)
	{
		handle->stateConfVector[i] = Robot_template_last_state;
	}
	
	
	handle->stateConfVectorPosition = 0;
	
	clearInEvents(handle);
	clearOutEvents(handle);
	
	/* Default init sequence for statechart robot_template */
	handle->iface.button = bool_false;
	handle->iface.prev_encoder = 0;
	handle->iface.angle = 0.0f;
	handle->iface.cliffLeft = bool_false;
	handle->iface.cliffRight = bool_false;
	handle->iface.theta = 0.0f;
	handle->iface.psi = 0.0f;
	handle->iface.dist = 0.0f;
	handle->iface.x_off = 0.0f;
}

void robot_template_enter(Robot_template* handle)
{
	/* Default enter sequence for statechart robot_template */
	enseq_main_region_default(handle);
}

void robot_template_runCycle(Robot_template* handle)
{
	clearOutEvents(handle);
	for (handle->stateConfVectorPosition = 0;
		handle->stateConfVectorPosition < ROBOT_TEMPLATE_MAX_ORTHOGONAL_STATES;
		handle->stateConfVectorPosition++)
		{
			
		switch (handle->stateConfVector[handle->stateConfVectorPosition])
		{
		case Robot_template_main_region_OFF:
		{
			main_region_OFF_react(handle, bool_true);
			break;
		}
		case Robot_template_main_region_DRIVING:
		{
			main_region_DRIVING_react(handle, bool_true);
			break;
		}
		case Robot_template_main_region_LEFT:
		{
			main_region_LEFT_react(handle, bool_true);
			break;
		}
		case Robot_template_main_region_RIGHT:
		{
			main_region_RIGHT_react(handle, bool_true);
			break;
		}
		default:
			break;
		}
	}
	
	clearInEvents(handle);
}

void robot_template_exit(Robot_template* handle)
{
	/* Default exit sequence for statechart robot_template */
	exseq_main_region(handle);
}

sc_boolean robot_template_isActive(const Robot_template* handle)
{
	sc_boolean result = bool_false;
	sc_integer i;
	
	for(i = 0; i < ROBOT_TEMPLATE_MAX_ORTHOGONAL_STATES; i++)
	{
		result = result || handle->stateConfVector[i] != Robot_template_last_state;
	}
	
	return result;
}

/* 
 * Always returns 'false' since this state machine can never become final.
 */
sc_boolean robot_template_isFinal(const Robot_template* handle)
{
(void)(handle);
return bool_false;

}

sc_boolean robot_template_isStateActive(const Robot_template* handle, Robot_templateStates state)
{
	sc_boolean result = bool_false;
	switch (state)
	{
		case Robot_template_main_region_OFF :
			result = (sc_boolean) (handle->stateConfVector[SCVI_ROBOT_TEMPLATE_MAIN_REGION_OFF] == Robot_template_main_region_OFF
			);
			break;
		case Robot_template_main_region_DRIVING :
			result = (sc_boolean) (handle->stateConfVector[SCVI_ROBOT_TEMPLATE_MAIN_REGION_DRIVING] == Robot_template_main_region_DRIVING
			);
			break;
		case Robot_template_main_region_LEFT :
			result = (sc_boolean) (handle->stateConfVector[SCVI_ROBOT_TEMPLATE_MAIN_REGION_LEFT] == Robot_template_main_region_LEFT
			);
			break;
		case Robot_template_main_region_RIGHT :
			result = (sc_boolean) (handle->stateConfVector[SCVI_ROBOT_TEMPLATE_MAIN_REGION_RIGHT] == Robot_template_main_region_RIGHT
			);
			break;
		default:
			result = bool_false;
			break;
	}
	return result;
}

static void clearInEvents(Robot_template* handle)
{
}

static void clearOutEvents(Robot_template* handle)
{
}



sc_boolean robot_templateIface_get_button(const Robot_template* handle)
{
	return handle->iface.button;
}
void robot_templateIface_set_button(Robot_template* handle, sc_boolean value)
{
	handle->iface.button = value;
}
uint16_t robot_templateIface_get_prev_encoder(const Robot_template* handle)
{
	return handle->iface.prev_encoder;
}
void robot_templateIface_set_prev_encoder(Robot_template* handle, uint16_t value)
{
	handle->iface.prev_encoder = value;
}
float robot_templateIface_get_angle(const Robot_template* handle)
{
	return handle->iface.angle;
}
void robot_templateIface_set_angle(Robot_template* handle, float value)
{
	handle->iface.angle = value;
}
sc_boolean robot_templateIface_get_cliffLeft(const Robot_template* handle)
{
	return handle->iface.cliffLeft;
}
void robot_templateIface_set_cliffLeft(Robot_template* handle, sc_boolean value)
{
	handle->iface.cliffLeft = value;
}
sc_boolean robot_templateIface_get_cliffRight(const Robot_template* handle)
{
	return handle->iface.cliffRight;
}
void robot_templateIface_set_cliffRight(Robot_template* handle, sc_boolean value)
{
	handle->iface.cliffRight = value;
}
float robot_templateIface_get_theta(const Robot_template* handle)
{
	return handle->iface.theta;
}
void robot_templateIface_set_theta(Robot_template* handle, float value)
{
	handle->iface.theta = value;
}
float robot_templateIface_get_psi(const Robot_template* handle)
{
	return handle->iface.psi;
}
void robot_templateIface_set_psi(Robot_template* handle, float value)
{
	handle->iface.psi = value;
}
float robot_templateIface_get_dist(const Robot_template* handle)
{
	return handle->iface.dist;
}
void robot_templateIface_set_dist(Robot_template* handle, float value)
{
	handle->iface.dist = value;
}
float robot_templateIface_get_x_off(const Robot_template* handle)
{
	return handle->iface.x_off;
}
void robot_templateIface_set_x_off(Robot_template* handle, float value)
{
	handle->iface.x_off = value;
}

/* implementations of all internal functions */

/* Entry action for state 'OFF'. */
static void enact_main_region_OFF(Robot_template* handle)
{
	/* Entry action for state 'OFF'. */
	handle->iface.button = bool_false;
}

/* Entry action for state 'DRIVING'. */
static void enact_main_region_DRIVING(Robot_template* handle)
{
	/* Entry action for state 'DRIVING'. */
	handle->iface.button = bool_false;
	handle->iface.theta = 0.0f;
}

/* Entry action for state 'LEFT'. */
static void enact_main_region_LEFT(Robot_template* handle)
{
	/* Entry action for state 'LEFT'. */
	handle->iface.button = bool_false;
}

/* Entry action for state 'RIGHT'. */
static void enact_main_region_RIGHT(Robot_template* handle)
{
	/* Entry action for state 'RIGHT'. */
	handle->iface.button = bool_false;
}

/* 'default' enter sequence for state OFF */
static void enseq_main_region_OFF_default(Robot_template* handle)
{
	/* 'default' enter sequence for state OFF */
	enact_main_region_OFF(handle);
	handle->stateConfVector[0] = Robot_template_main_region_OFF;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state DRIVING */
static void enseq_main_region_DRIVING_default(Robot_template* handle)
{
	/* 'default' enter sequence for state DRIVING */
	enact_main_region_DRIVING(handle);
	handle->stateConfVector[0] = Robot_template_main_region_DRIVING;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state LEFT */
static void enseq_main_region_LEFT_default(Robot_template* handle)
{
	/* 'default' enter sequence for state LEFT */
	enact_main_region_LEFT(handle);
	handle->stateConfVector[0] = Robot_template_main_region_LEFT;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state RIGHT */
static void enseq_main_region_RIGHT_default(Robot_template* handle)
{
	/* 'default' enter sequence for state RIGHT */
	enact_main_region_RIGHT(handle);
	handle->stateConfVector[0] = Robot_template_main_region_RIGHT;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for region main region */
static void enseq_main_region_default(Robot_template* handle)
{
	/* 'default' enter sequence for region main region */
	react_main_region__entry_Default(handle);
}

/* Default exit sequence for state OFF */
static void exseq_main_region_OFF(Robot_template* handle)
{
	/* Default exit sequence for state OFF */
	handle->stateConfVector[0] = Robot_template_last_state;
	handle->stateConfVectorPosition = 0;
}

/* Default exit sequence for state DRIVING */
static void exseq_main_region_DRIVING(Robot_template* handle)
{
	/* Default exit sequence for state DRIVING */
	handle->stateConfVector[0] = Robot_template_last_state;
	handle->stateConfVectorPosition = 0;
}

/* Default exit sequence for state LEFT */
static void exseq_main_region_LEFT(Robot_template* handle)
{
	/* Default exit sequence for state LEFT */
	handle->stateConfVector[0] = Robot_template_last_state;
	handle->stateConfVectorPosition = 0;
}

/* Default exit sequence for state RIGHT */
static void exseq_main_region_RIGHT(Robot_template* handle)
{
	/* Default exit sequence for state RIGHT */
	handle->stateConfVector[0] = Robot_template_last_state;
	handle->stateConfVectorPosition = 0;
}

/* Default exit sequence for region main region */
static void exseq_main_region(Robot_template* handle)
{
	/* Default exit sequence for region main region */
	/* Handle exit of all possible states (of robot_template.main_region) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case Robot_template_main_region_OFF :
		{
			exseq_main_region_OFF(handle);
			break;
		}
		case Robot_template_main_region_DRIVING :
		{
			exseq_main_region_DRIVING(handle);
			break;
		}
		case Robot_template_main_region_LEFT :
		{
			exseq_main_region_LEFT(handle);
			break;
		}
		case Robot_template_main_region_RIGHT :
		{
			exseq_main_region_RIGHT(handle);
			break;
		}
		default: break;
	}
}

/* Default react sequence for initial entry  */
static void react_main_region__entry_Default(Robot_template* handle)
{
	/* Default react sequence for initial entry  */
	enseq_main_region_OFF_default(handle);
}

static sc_boolean react(Robot_template* handle) {
	/* State machine reactions. */
	return bool_false;
}

static sc_boolean main_region_OFF_react(Robot_template* handle, const sc_boolean try_transition) {
	/* The reactions of state OFF. */
	sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if ((react(handle)) == (bool_false))
		{ 
			if (handle->iface.button == bool_true)
			{ 
				exseq_main_region_OFF(handle);
				enseq_main_region_DRIVING_default(handle);
			}  else
			{
				did_transition = bool_false;
			}
		} 
	} 
	if ((did_transition) == (bool_false))
	{ 
		stop_kobuki();
		handle->iface.button = is_button_press();
		print_state(OFF);
		print_angle(read_tilt_theta());
	} 
	return did_transition;
}

static sc_boolean main_region_DRIVING_react(Robot_template* handle, const sc_boolean try_transition) {
	/* The reactions of state DRIVING. */
	sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if ((react(handle)) == (bool_false))
		{ 
			if ((handle->iface.theta) > (10))
			{ 
				exseq_main_region_DRIVING(handle);
				enseq_main_region_LEFT_default(handle);
			}  else
			{
				if ((handle->iface.theta) < (10))
				{ 
					exseq_main_region_DRIVING(handle);
					enseq_main_region_RIGHT_default(handle);
				}  else
				{
					did_transition = bool_false;
				}
			}
		} 
	} 
	if ((did_transition) == (bool_false))
	{ 
		drive_kobuki(150, 150);
		handle->iface.button = is_button_press();
		handle->iface.theta = get_theta();
	} 
	return did_transition;
}

static sc_boolean main_region_LEFT_react(Robot_template* handle, const sc_boolean try_transition) {
	/* The reactions of state LEFT. */
	sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if ((react(handle)) == (bool_false))
		{ 
			if (((handle->iface.theta) < (10)) && ((handle->iface.theta) > (0)))
			{ 
				exseq_main_region_LEFT(handle);
				enseq_main_region_DRIVING_default(handle);
			}  else
			{
				did_transition = bool_false;
			}
		} 
	} 
	if ((did_transition) == (bool_false))
	{ 
		drive_kobuki(100, 150);
		handle->iface.button = is_button_press();
		handle->iface.theta = get_theta();
	} 
	return did_transition;
}

static sc_boolean main_region_RIGHT_react(Robot_template* handle, const sc_boolean try_transition) {
	/* The reactions of state RIGHT. */
	sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if ((react(handle)) == (bool_false))
		{ 
			if (((handle->iface.theta) < (10)) && ((handle->iface.theta) > (0)))
			{ 
				exseq_main_region_RIGHT(handle);
				enseq_main_region_DRIVING_default(handle);
			}  else
			{
				did_transition = bool_false;
			}
		} 
	} 
	if ((did_transition) == (bool_false))
	{ 
		drive_kobuki(150, 100);
		handle->iface.button = is_button_press();
		handle->iface.theta = get_theta();
	} 
	return did_transition;
}


